import { Document, Page, Text, View } from '@react-pdf/renderer';
import { pdfStyles as s } from '../styles';

export type ReceiptDocumentData = {
  number: string;
  issuedAt: string;
  concept: string;
  amount: string;
  balanceAfter: string;
  method: string;
  reference?: string;
  ownerName: string;
  tenantName: string;
  propertyName: string;
  appName: string;
};

/**
 * A polished payment receipt. Pure presentation — all values are pre-formatted
 * strings so the document has no dependency on locale/formatting logic.
 */
export function ReceiptDocument({ data }: { data: ReceiptDocumentData }) {
  return (
    <Document
      title={`Receipt ${data.number}`}
      author={data.ownerName}
      creator={data.appName}
    >
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.brand}>{data.appName}</Text>
            <Text style={s.mutedText}>Payment receipt</Text>
          </View>
          <View style={s.docMeta}>
            <Text style={s.docTitle}>Receipt</Text>
            <Text style={s.mutedText}>{data.number}</Text>
            <Text style={s.mutedText}>{data.issuedAt}</Text>
          </View>
        </View>

        <View style={s.grid}>
          <View style={s.col}>
            <Text style={s.label}>Received from</Text>
            <Text style={s.value}>{data.tenantName}</Text>
            <Text style={s.mutedText}>{data.propertyName}</Text>
          </View>
          <View style={s.col}>
            <Text style={s.label}>Received by</Text>
            <Text style={s.value}>{data.ownerName}</Text>
          </View>
        </View>

        <View style={s.divider} />

        <View style={s.tableHeader}>
          <Text style={[s.cellLabel, { width: '60%' }]}>Concept</Text>
          <Text style={[s.cellLabel, { width: '40%', textAlign: 'right' }]}>
            Amount
          </Text>
        </View>
        <View style={s.tableRow}>
          <Text style={{ width: '60%' }}>{data.concept}</Text>
          <Text style={{ width: '40%', textAlign: 'right' }}>
            {data.amount}
          </Text>
        </View>

        <View style={s.totalRow}>
          <Text style={s.totalLabel}>Total paid</Text>
          <Text style={s.totalValue}>{data.amount}</Text>
        </View>

        <View style={[s.section, { marginTop: 24 }]}>
          <View style={s.grid}>
            <View style={s.col}>
              <Text style={s.label}>Payment method</Text>
              <Text>{data.method}</Text>
            </View>
            <View style={s.col}>
              <Text style={s.label}>Outstanding balance</Text>
              <Text>{data.balanceAfter}</Text>
            </View>
          </View>
          {data.reference ? (
            <View style={{ marginTop: 12 }}>
              <Text style={s.label}>Reference</Text>
              <Text>{data.reference}</Text>
            </View>
          ) : null}
        </View>

        <Text style={s.footer} fixed>
          Generated by {data.appName}. This receipt confirms the payment
          detailed above.
        </Text>
      </Page>
    </Document>
  );
}
