import { Document, Page, Text, View } from '@react-pdf/renderer';
import { pdfStyles as s } from '../styles';

export type StatementLine = {
  date: string;
  concept: string;
  amount: string;
};

export type StatementDocumentData = {
  number: string;
  periodLabel: string;
  ownerName: string;
  tenantName: string;
  propertyName: string;
  lines: StatementLine[];
  totalCharged: string;
  totalPaid: string;
  outstanding: string;
  nextDueDate?: string;
  appName: string;
};

/** Monthly statement summarising charges, payments and outstanding balance. */
export function StatementDocument({
  data,
}: {
  data: StatementDocumentData;
}) {
  return (
    <Document
      title={`Statement ${data.number}`}
      author={data.ownerName}
      creator={data.appName}
    >
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.brand}>{data.appName}</Text>
            <Text style={s.mutedText}>Monthly statement</Text>
          </View>
          <View style={s.docMeta}>
            <Text style={s.docTitle}>Statement</Text>
            <Text style={s.mutedText}>{data.number}</Text>
            <Text style={s.mutedText}>{data.periodLabel}</Text>
          </View>
        </View>

        <View style={s.grid}>
          <View style={s.col}>
            <Text style={s.label}>Tenant</Text>
            <Text style={s.value}>{data.tenantName}</Text>
            <Text style={s.mutedText}>{data.propertyName}</Text>
          </View>
          <View style={s.col}>
            <Text style={s.label}>Owner</Text>
            <Text style={s.value}>{data.ownerName}</Text>
          </View>
        </View>

        <View style={s.divider} />

        <View style={s.tableHeader}>
          <Text style={[s.cellLabel, { width: '20%' }]}>Date</Text>
          <Text style={[s.cellLabel, { width: '55%' }]}>Concept</Text>
          <Text style={[s.cellLabel, { width: '25%', textAlign: 'right' }]}>
            Amount
          </Text>
        </View>
        {data.lines.length === 0 ? (
          <View style={s.tableRow}>
            <Text style={s.mutedText}>No payments recorded this period.</Text>
          </View>
        ) : (
          data.lines.map((line, index) => (
            <View style={s.tableRow} key={index}>
              <Text style={{ width: '20%' }}>{line.date}</Text>
              <Text style={{ width: '55%' }}>{line.concept}</Text>
              <Text style={{ width: '25%', textAlign: 'right' }}>
                {line.amount}
              </Text>
            </View>
          ))
        )}

        <View style={{ marginTop: 20, alignItems: 'flex-end' }}>
          <SummaryRow label="Total charged" value={data.totalCharged} />
          <SummaryRow label="Total paid" value={data.totalPaid} />
          <View style={[s.totalRow, { width: 240 }]}>
            <Text style={s.totalLabel}>Outstanding</Text>
            <Text style={s.totalValue}>{data.outstanding}</Text>
          </View>
          {data.nextDueDate ? (
            <Text style={[s.mutedText, { marginTop: 8 }]}>
              Next payment due {data.nextDueDate}
            </Text>
          ) : null}
        </View>

        <Text style={s.footer} fixed>
          Generated by {data.appName}.
        </Text>
      </Page>
    </Document>
  );
}

function SummaryRow({ label, value }: { label: string; value: string }) {
  return (
    <View
      style={{
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: 240,
        paddingVertical: 3,
      }}
    >
      <Text style={s.mutedText}>{label}</Text>
      <Text>{value}</Text>
    </View>
  );
}
